---

- name: install rabbitmq-server dependencies (RedHat)
  yum:
    name:
#      - erlang
      - libselinux-python
      - "{{ erlang_rpm | default('https://github.com/rabbitmq/erlang-rpm/releases/download/v22.0.4/erlang-22.0.4-1.el7.x86_64.rpm') }}"
      - iproute
    state: present
  register: pkg_result
  until: pkg_result is success

- name: download rabbitmq rpm signature
  get_url:
    url: https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    dest: /root/rabbitmq-signing-key-public.asc
    mode: 0644

- name: import rabbitmq rpm repository signature
  rpm_key:
    state: present
    key: /root/rabbitmq-signing-key-public.asc

## FIXME! ansible not detecting package already installed if http
- name: check if rabbitmq-server installed
  command: rpm -q rabbitmq-server
  register: rpm
  changed_when: false
  ignore_errors: true
  args:
    warn: false

- name: install rabbitmq-server (RedHat)
  yum:
    name:
      - https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.15/rabbitmq-server-3.7.15-1.el7.noarch.rpm
    state: present
  when: rpm is defined and rpm.rc != 0
  register: pkg_result
  until: pkg_result is success

- name: enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes state=started
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")
